#!/usr/bin/env python3
"""R251 deterministic target-free production-shape fixture replay.

No ARC/public/private targets are read. The fixture is a zero-bias width-1024,
depth-16 MLP driven by one Gaussian latent coordinate. Because every layer is
positively homogeneous, each post-ReLU neuron is exactly two-ray linear:
a_plus*z for z>0 and a_minus*(-z) for z<0. Therefore the exact mean is
(a_plus+a_minus)/sqrt(2*pi), computed in float64 only for the target-free truth.
Weights are generated by a fixed uint32 integer hash, not an RNG implementation.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np

WIDTH = 1024
DEPTH = 16
SEEDS = (251001, 251002)
SCALE = np.float64(0.05412658773652741)
INV_SQRT_2PI = np.float64(0.3989422804014327)
U32_DEN = np.float64(4294967296.0)


def _hash_u32(seed: int, layer: int, size: int) -> np.ndarray:
    idx = np.arange(size, dtype=np.uint32)
    x = idx + np.uint32(seed) + np.uint32((layer * 0x9E3779B9) & 0xFFFFFFFF)
    x ^= x >> np.uint32(16)
    x *= np.uint32(0x7FEB352D)
    x ^= x >> np.uint32(15)
    x *= np.uint32(0x846CA68B)
    x ^= x >> np.uint32(16)
    return x


def layer_weight(seed: int, layer: int) -> np.ndarray:
    size = WIDTH if layer == 0 else WIDTH * WIDTH
    x = _hash_u32(seed, layer, size)
    u = (x.astype(np.float64) + np.float64(0.5)) / U32_DEN
    vals = ((np.float64(2.0) * u - np.float64(1.0)) * SCALE).astype("<f4")
    if layer == 0:
        w = np.zeros((WIDTH, WIDTH), dtype="<f4")
        w[0, :] = vals
        return w
    return vals.reshape(WIDTH, WIDTH)


def fixture(seed: int) -> dict:
    a_plus = None
    a_minus = None
    weight_hashes = []
    truth_hashes = []
    truths = []
    for layer in range(DEPTH):
        w = layer_weight(seed, layer)
        weight_hashes.append(hashlib.sha256(w.tobytes(order="C")).hexdigest())
        if layer == 0:
            row = w[0, :].astype(np.float64)
            a_plus = np.maximum(row, np.float64(0.0))
            a_minus = np.maximum(-row, np.float64(0.0))
        else:
            wt = w.T.astype(np.float64)
            a_plus = np.maximum(wt @ a_plus, np.float64(0.0))
            a_minus = np.maximum(wt @ a_minus, np.float64(0.0))
        truth = ((a_plus + a_minus) * INV_SQRT_2PI).astype("<f8")
        truths.append(truth)
        truth_hashes.append(hashlib.sha256(truth.tobytes(order="C")).hexdigest())
    truth_tensor = np.stack(truths, axis=0).astype("<f8")
    return {
        "seed": seed,
        "width": WIDTH,
        "depth": DEPTH,
        "weight_layer_sha256": weight_hashes,
        "weights_aggregate_sha256": hashlib.sha256(
            b"".join(bytes.fromhex(x) for x in weight_hashes)
        ).hexdigest(),
        "truth_layer_sha256": truth_hashes,
        "truth_tensor_sha256": hashlib.sha256(
            truth_tensor.tobytes(order="C")
        ).hexdigest(),
        "truth_shape": [DEPTH, WIDTH],
    }


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--output", required=True)
    args = p.parse_args()
    out = {
        "schema": "r251-target-free-fixtures-v1",
        "construction": (
            "one-latent zero-bias production-shape MLP; deterministic uint32 "
            "hash weights; exact two-ray Gaussian expectation"
        ),
        "weight_scale_literal": float(SCALE),
        "inv_sqrt_2pi_literal": float(INV_SQRT_2PI),
        "fixtures": [fixture(seed) for seed in SEEDS],
    }
    Path(args.output).write_text(
        json.dumps(out, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
